### ISSUE TITLE
Multiple '-e' options break with single quote

### ISSUE THREAD

**Issue by spacewander** [openresty/resty-cli#14]
For example, run:
`resty -e "print('a')" -e "print(1)"`
And got:
`nginx: [emerg] unexpected "a" in /var/folders/65/qbj3jwt50tn2sfc4lg8lgvsc0000gn/T/qu7Vp7jYf6/conf/nginx.conf:146`.

After debugging, I found it is the single quote which we should blame:
```
init_worker_by_lua '
        ...
arg[-3] = [=[-e]=]
arg[-2] = [=[print('a')]=] # string breaks here
```

So here will be two ways to fix it:
1. quote the argument string
2. update `init_worker_by_lua` to `init_worker_by_lua_block`

I am not sure which one is better...

**Comment by agentzh** [comment]
@spacewander Thanks for the report! Just fixed in git master.

**Comment by spacewander** [comment]
Maybe we also need to be update the ngx_lua required version?
https://github.com/openresty/resty-cli/blob/e4a620d72ca7be5ee6138070237bbe777e1d0ed1/bin/resty#L318

**Comment by agentzh** [comment]
@spacewander You're welcome to create another PR for the ngx_lua version checks. Thanks!
