### ISSUE TITLE
OpenResty 1.11.2.3 yum package does not include resty-cli

### ISSUE THREAD

**Issue by whiskeysauer** [openresty/resty-cli#28]
Just installed openresty 1.11.2.3 on Centos 7. I immediately tried "resty" and got command not found. I checked the path, and there is no "resty" in the bin folder.

Was this removed from the bundle? The openresty docs (installation) section still tells us that the first thing to try is a hello world using the bundled  "resty" script. but it's simply not there.

Can someone confirm this was removed?

**Comment by whiskeysauer** [comment]
To fix this problem...

I downloaded the source and copied the resty-cli files to the proper bin folder in my installation. That works.

But someone should be aware that the current CENTOS 7 binary package does not install resty-cli - as the docs say it does.

**Comment by agentzh** [comment]
@whiskeysauer It is in a separate package named `openresty-resty`:

```
$ repoquery -l openresty-resty
/usr/bin/resty
/usr/local/openresty/bin/resty
```

And it is officially documented here:

http://openresty.org/en/rpm-packages.html#openresty-resty
