### ISSUE TITLE
Implement luajit's `-jv` and `-jdump` options in resty

### ISSUE THREAD

**Issue by agentzh** [openresty/resty-cli#29]
It would be great if resty can implement luajit utility's command line options `-jv`, `-jdump` and etc.

**Comment by mikz** [comment]
As a workaround you can require those libraries and execute them from lua:

```lua
require("jit.v").start("dump.txt")
require('jit.p').start('vl')
require('jit.dump').start('bsx', 'jit.log')
```

**Comment by agentzh** [comment]
@mikz Yeah, that's what we've been doing ourselves, just not very convenient.

**Comment by agentzh** [comment]
@mikz Actually you can use `-e 'require "jit.v".start("/dev/stderr")` directly on the command line and make it a shell alias, for example.

**Comment by agentzh** [comment]
@mikz OK, already implemented in master. But we need to use `resty -j v` and `resty -j dump` respectively.
