### ISSUE TITLE
Why not use content_by_lua?

### ISSUE THREAD

**Issue by DoBetter-pan** [openresty/resty-cli#33]
I am not familiar with Perl. But I read the code of resty. I think it creates a config file nginx.conf, then starts openresty with this file. The codes are executed in init_worker_by_lua_block. Why not create a config file  nginx.conf and start openresty, then curl the server?  If so,  content_by_lua can be used. We can test the code with different URL and cookie.  We can test the codes that deal with cookie, the codes that deal with url parameter.... is it achievable？Thanks!

**Comment by agentzh** [comment]
@DoBetter-pan The `resty` tool is not really for testing OpenResty servers. We provide `Test::Nginx` for it and it is used to drive almost all our OpenResty components and libraries' test suites.

The `resty` tool is for running command-line OpenResty scripts which has nothing to do with OpenResty servers. We surely do not want to incur that overhead when we run pure console-based OpenResty utilities.
