### ISSUE TITLE
Does the resty command have any special integration operations for openssl？

### ISSUE THREAD

**Issue by shakaijian** [openresty/resty-cli#36]
Does the resty command have any special integration operations for openssl?Why is it that the same lua script, using luajit command with error reporting, using resty command with no problem, the luajit execution report is  “undefined symbol: BIO_new_mem_buf ”，this is the method of openssl. How to solve this problem?

**Comment by agentzh** [comment]
@shakaijian Maybe you should use the official pre-built OpenResty packages here?

https://openresty.org/en/linux-packages.html

**Comment by agentzh** [comment]
@shakaijian Sorry, please ignore my previous comment. The `resty` command invokes nginx which sets RPATH so that it can loads the correct version of openssl.
