### ISSUE TITLE
resty's ngx object is missing many fields

### ISSUE THREAD

**Issue by ktalebian** [openresty/resty-cli#48]
We use `resty` for running tests. However, it looks like resty's `ngx` is still missing properties, forcing us to `mock` out ngx as so:

```lua
package.path = package.path .. ';/?.lua'

local pl = require 'pl.import_into'()

_G.ngx = pl.tablex.merge(pl.tablex.deepcopy(ngx),
    {
        req = {
            get_method = function() end,
            get_post_args = function() end,
            get_body_data = function() end,
            set_header = function() end,
            read_body = function() end,
            get_uri_args = function() return {} end

        },
        socket = {
            udp = function()
                return {
                    setpeername = function() return true end,
                    send = function() end,
                    close = function() end
                }
            end
        },
        timer = {
            at = function(delay, handler, ...)
                local msec = delay
                if delay > 100 then msec = delay/1000 end
                os.execute('sleep ' .. delay)
                handler(...)
            end
        },
        header = {},
        unescape_uri = function(str) return str end,
        escape_uri = function(str)
            return tostring(str):gsub("\n", "\r\n"):gsub("([^%w_ ])", function (c)
                return string.format("%%%02X", string.byte(c))
            end):gsub(" ", "+")
        end
    }, true
)

return _G.ngx
```

These are at least the methods/vars that I care about and have found to be missing. Any ideas why?

**Comment by agentzh** [comment]
@ktalebian Well, the resty utility is headless so it is not meant to serve http requests or anything like that. The Lua code is running in a 0-delay timer created in `init_worker_by_lua*`. So it won't have those request-context API, for obvious reasons. Mocking is not the recommended way to test your OpenResty app. Your mocked API may hide many important details. You really need to test the real HTTP thing for as much coverage as possible. And we usually use the `Test::Nginx` test scaffold for that. See

https://openresty.gitbooks.io/programming-openresty/content/testing/

**Comment by ktalebian** [comment]
@agentzh that looks great and I'll be using that too. But I also would like to write some unit-tests. `Test::Nginx` doesn't look like it's for unit-testing.

**Comment by agentzh** [comment]
@ktalebian Well, it is still capable. For example,

https://github.com/openresty/lua-resty-core/blob/master/t/decode-base64.t
