### ISSUE TITLE
How can I use resty to debug ngx-lua

### ISSUE THREAD

**Issue by zs-soft** [openresty/resty-cli#51]
We Use idea&emmy-lua plugin  to debug by luajit is worked. 
![image](https://user-images.githubusercontent.com/45423321/57522378-1c8e1a00-7355-11e9-9b5e-59d7f7e1f07e.png)

This program used like this, can output result,but can not debug.
![image](https://user-images.githubusercontent.com/45423321/57522398-2c0d6300-7355-11e9-99f0-1e83fdd4fc3b.png)

![image](https://user-images.githubusercontent.com/45423321/57522436-41828d00-7355-11e9-9f15-e3f2c5203e79.png)

**Comment by agentzh** [comment]
We are not familiar with that debugger so we cannot really help. I think you should contact the maintainers of that debugger for support instead?

**Comment by zs-soft** [comment]
By default lua/luajit mobdebug  is working，resty-cli can execute the lua script，I thought it could be debug too. Thank you any way！

**Comment by rulatir** [comment]
There is a big meta-problem with openresty. The responsibility for making Lua debuggers work with openresty is being ping-ponged betweel authors of Lua debuggers and authors of openresty. As a result, problems with debugging remain unsolved for years.
