### ISSUE TITLE
command line arguments are not working with openresty/1.19.3.1, resty 0.27

### ISSUE THREAD

**Issue by zcaudate** [openresty/resty-cli#66]
I tried to run the example for command line arguments and it doesn't seem to work

```
❯  resty -e 'print(arg[1], ", ", arg[2])' hello world
Lua input file hello not found.
```

<img width="890" alt="Screen Shot 2021-01-25 at 7 19 48 pm" src="https://user-images.githubusercontent.com/1455572/105699621-9f4c7380-5f42-11eb-9375-895247848bfe.png">

**Comment by suikabreaker** [comment]
this is not how this utility supposed to be used. check `resty --help`.

**Comment by zcaudate** [comment]
I don't understand what you're talking about. This is a screenshot of the readme on the current project's page

https://github.com/openresty/resty-cli/blob/master/README.md

<img width="947" alt="Screen Shot 2021-05-09 at 8 21 09 pm" src="https://user-images.githubusercontent.com/1455572/117572147-1a0d5900-b104-11eb-8719-ef8d88e345ad.png">

**Comment by zcaudate** [comment]
@xiaocang thanks it's working for me now.

**Comment by cloudspeech** [comment]
# resty -V
resty 0.23
nginx version: openresty/1.15.8.2
# resty -e 'print(arg[1], ", ", arg[2])' /dev/null hello world
Lua input file /dev/null not found.

**Comment by cloudspeech** [comment]
Workaround: 

# dummyluafile=$(mktemp --suffix=.lua); resty -e 'print(arg[1], ", ", arg[2])' $dummyluafile hello world
hello, world
