### ISSUE TITLE
Support multiple -e and luafile together

### ISSUE THREAD

**Issue by DorianGray** [openresty/resty-cli#7]
Right now, if you run `resty -e 'print("1")' -e 'print("2")' 'myfile' ` where myfile prints 3, only '2' is printed.

Running the same arguments through luajit results in 1, 2 and 3 being printed in order. It would be nice if they were a little closer functionally, particularly for testing.

**Comment by agentzh** [comment]
@DorianGray Yeah, it would be a good thing to have, just like the `luajit` executable. Will you contribute a patch for that? Thanks!

**Comment by DorianGray** [comment]
https://github.com/openresty/resty-cli/pull/8
